apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemq-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemq-consumer
  template:
    metadata:
      labels:
        app: nodemq-consumer
    spec:
      containers:
      - name: nodemq-consumer
        imagePullPolicy: Never
        image: bencoderus/nodemq
        env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: nodemq-secret
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nodemq-secret
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_HOST
            value: nodemq-rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
        command:
        - yarn
        - run
        - consume