apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemq-producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemq-producer
  template:
    metadata:
      labels:
        app: nodemq-producer
    spec:
      containers:
      - name: nodemq-producer
        imagePullPolicy: Never
        image: bencoderus/nodemq
        env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: nodemq-secret
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nodemq-secret
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_HOST
            value: nodemq-rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
        command:
        - yarn
        - run
        - start
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodemq-producer-service
spec:
  type: LoadBalancer
  selector:
    app: nodemq-producer
  ports:
  - port: 3000
    targetPort: 3000
