apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemq-rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: nodemq-rabbitmq
  template:
    metadata:
      labels:
        app: nodemq-rabbitmq
    spec:
      containers:
      - name: nodemq-rabbitmq
        image: rabbitmq:3.10.5-management-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: nodemq-secret
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: nodemq-secret
                key: RABBITMQ_PASSWORD
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: nodemq-rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: nodemq-rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
