apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mq-rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: node-mq-rabbitmq
  template:
    metadata:
      labels:
        app: node-mq-rabbitmq
    spec:
      containers:
      - name: node-mq-rabbitmq
        image: rabbitmq:3.10.5-management-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: node-mq-secret
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: node-mq-secret
                key: RABBITMQ_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: node-mq-rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: node-mq-rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
